Update README with information on the annotations
stolostron/governance-policy-addon-controller pull request #26
Opened 2022-03-23 18:28 UTC by JustinKuli

This documents the stand-alone annotations we currently have.

Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

2022-03-23 19:48 UTC, dhaiducek requested changes
Looks great! I'm a little embarrassed I didn't add these docs along with my PR!

Minor update requested.

2022-03-23 19:48 UTC, dhaiducek commented on README.md
> +be modified in with the `addon.open-cluster-management.io/values` annotation. However, the structure
```suggestion
be modified with the `addon.open-cluster-management.io/values` annotation. However, the structure
```

2022-03-23 21:23 UTC, dhaiducek commented
Please check DCO here.

2022-03-24 12:42 UTC, JustinKuli commented
Sorry, I didn't realize that the `Signed-off-by` needed to be separated from the `Co-authored-by` by a blank line.

2022-03-24 18:43 UTC, merged