Remove the IAM Policy Controller
stolostron/governance-policy-addon-controller pull request #514
Opened 2024-04-23 18:22 UTC by yiraeChristineKim

Ref: https://issues.redhat.com/browse/HYPBLD-314

2024-04-24 14:22 UTC, dhaiducek commented on config/rbac/role.yaml
> +  - delete
Actually, maybe add another item that just has `delete` for `iam-policy-controller`. That's probably the most targeted.

2024-04-24 14:27 UTC, dhaiducek commented
> Should I add an e2e- test about cleaning clusteramangementAddon?

Yes, I think so.

2024-04-24 14:44 UTC, mprahl commented
/hold while we discuss this with the Hub installer team on if multicluster-hub should handle deleting the CMA.

2024-04-24 14:51 UTC, dhaiducek commented
> /hold while we discuss this with the Hub installer team on if multicluster-hub should handle deleting the CMA.

@yiraeChristineKim Would you move the `delete` changes over to a separate PR? The other changes could get merged as-is in my opinion.

2024-04-29 13:17 UTC, mprahl commented on pkg/addon/deleteaddon/deleate_addon.go
> +package deleteaddon
Could you please delete this file now that the uninstall is happening in the multiclusterhub-operator?

2024-04-29 14:16 UTC, mprahl commented on main.go
> +//+kubebuilder:rbac:groups=addon.open-cluster-management.io,resources=clustermanagementaddons,verbs=get;list;watch;delete
```suggestion
//+kubebuilder:rbac:groups=addon.open-cluster-management.io,resources=clustermanagementaddons,verbs=get;list;watch
```

2024-04-29 14:17 UTC, mprahl requested changes
The permission change can be reverted back now.

2024-04-29 14:27 UTC, yiraeChristineKim commented on main.go
> +//+kubebuilder:rbac:groups=addon.open-cluster-management.io,resources=clustermanagementaddons,verbs=get;list;watch;delete
done

2024-04-29 16:36 UTC, mprahl approved these changes

2024-04-29 16:37 UTC, mprahl commented
/unhold

2024-04-29 16:38 UTC, dhaiducek approved these changes

2024-04-29 16:42 UTC, merged