Add open-cluster-management-policies namespace to the managed and hub cluster
stolostron/governance-policy-addon-controller pull request #679
Opened 2024-09-23 16:01 UTC by yiraeChristineKim

Add open-cluster-management-policies namespace to the managed and hub cluster

Ref: https://issues.redhat.com/browse/ACM-13609

2024-09-24 13:31 UTC, yiraeChristineKim commented on test/e2e/case1_framework_deployment_test.go
> +			Kubectl("delete", "-n", cluster.clusterName, "-f", case1ManagedClusterAddOnCR, "--timeout=180s")
flaky test issue

2024-09-25 15:08 UTC, yiraeChristineKim commented
/cc @mprahl

2024-09-25 15:18 UTC, mprahl approved these changes

2024-09-25 15:20 UTC, mprahl commented
/hold

2024-09-25 15:21 UTC, mprahl requested changes
This PR needs to be in OCM-io.

2024-09-25 16:11 UTC, mprahl commented
Closing this one since it's covered in #684

2024-09-25 16:11 UTC, closed without merging